"use client";

import { FooterBar } from "@/components/footer-bar";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";

function SectionHeading({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="text-lg font-semibold tracking-tight mt-6 mb-3 first:mt-0">
      {children}
    </h2>
  );
}

function SubHeading({ children }: { children: React.ReactNode }) {
  return <h3 className="text-sm font-semibold mt-4 mb-1.5">{children}</h3>;
}

function Prose({ children }: { children: React.ReactNode }) {
  return (
    <div className="text-sm leading-relaxed text-muted-foreground space-y-2">
      {children}
    </div>
  );
}

function CodeBlock({ children }: { children: string }) {
  return (
    <pre className="mt-2 mb-3 overflow-x-auto rounded-lg border bg-muted/50 px-4 py-3 text-xs font-mono">
      {children}
    </pre>
  );
}

/* ------------------------------------------------------------------ */
/* Tab sections                                                        */
/* ------------------------------------------------------------------ */

function GettingStarted() {
  return (
    <div>
      <SectionHeading>What is Article Checker?</SectionHeading>
      <Prose>
        <p>
          Article Checker is a CLI tool and dashboard that runs multiple quality
          checks on your articles: plagiarism detection, AI content detection,
          SEO analysis, fact checking, tone-of-voice compliance, legal risk
          scanning, brief matching, and content summarization. It supports
          context management (tone guides, briefs, legal policies) and integrates
          with AI agents via an MCP server.
        </p>
        <p>
          Each check produces a score from 0 to 100 and a verdict of pass, warn,
          or fail. The overall score is the average of all enabled skill scores.
        </p>
      </Prose>

      <SectionHeading>Running your first check</SectionHeading>
      <Prose>
        <p>
          After installing, run the setup wizard to configure your API keys:
        </p>
      </Prose>
      <CodeBlock>{`bun run article-checker --setup`}</CodeBlock>
      <Prose>
        <p>Then check an article:</p>
      </Prose>
      <CodeBlock>{`bun run article-checker path/to/article.md`}</CodeBlock>
      <Prose>
        <p>Or launch the dashboard for a visual experience:</p>
      </Prose>
      <CodeBlock>{`bun run article-checker --ui`}</CodeBlock>

      <SectionHeading>Understanding scores</SectionHeading>
      <Prose>
        <p>
          Scores range from 0 to 100. The default thresholds (customizable in
          Settings) are:
        </p>
      </Prose>
      <div className="mt-2 space-y-1.5">
        <div className="flex items-center gap-2 text-sm">
          <Badge variant="default" className="bg-emerald-600">Pass</Badge>
          <span className="text-muted-foreground">75 or above</span>
        </div>
        <div className="flex items-center gap-2 text-sm">
          <Badge variant="secondary" className="bg-amber-500 text-white">Warn</Badge>
          <span className="text-muted-foreground">50 to 74</span>
        </div>
        <div className="flex items-center gap-2 text-sm">
          <Badge variant="destructive">Fail</Badge>
          <span className="text-muted-foreground">Below 50</span>
        </div>
      </div>
    </div>
  );
}

function SkillsReference() {
  const skills = [
    {
      name: "Plagiarism Check",
      engine: "Copyscape",
      cost: "~$0.09",
      desc: "Compares your article against billions of web pages to detect duplicated or closely paraphrased content. Returns matched URLs, percentage overlap, and specific quoted passages.",
    },
    {
      name: "AI Detection",
      engine: "Copyscape",
      cost: "~$0.09",
      desc: "Analyzes writing patterns to estimate the likelihood that content was generated by an AI model. Reports an AI probability percentage and flags specific passages.",
    },
    {
      name: "SEO Analysis",
      engine: "Offline",
      cost: "Free",
      desc: "Runs locally without any API calls. Checks word count, heading structure (H1-H6), readability score, keyword density, internal/external link counts, and list usage.",
    },
    {
      name: "Fact Check",
      engine: "Exa AI + MiniMax",
      cost: "~$0.02",
      desc: "Extracts factual claims from the article, searches for supporting or contradicting evidence via Exa AI, then uses MiniMax to assess confidence levels for each claim.",
    },
    {
      name: "Tone of Voice",
      engine: "MiniMax",
      cost: "~$0.01",
      desc: "Evaluates whether the article matches your brand voice guidelines. Automatically loads a tone-guide context if one has been uploaded via the Contexts page or CLI.",
    },
    {
      name: "Legal Risk",
      engine: "MiniMax",
      cost: "~$0.01",
      desc: "Scans for potential legal issues: unsubstantiated health claims, defamatory statements, false promises, missing disclaimers, and copyright concerns. Automatically loads a legal-policy context if available.",
    },
    {
      name: "Content Summary",
      engine: "MiniMax",
      cost: "~$0.01",
      desc: "Generates a structured summary: main topic, core argument, target audience, detected tone, and key takeaways. Useful for editorial review and metadata generation.",
    },
    {
      name: "Brief Matching",
      engine: "MiniMax",
      cost: "~$0.01",
      desc: "Checks the article against an uploaded content brief. Verifies coverage of required topics, audience alignment, and tone match. Requires a brief context uploaded via Contexts page or CLI.",
    },
  ];

  return (
    <div>
      <SectionHeading>Skills Reference</SectionHeading>
      <Prose>
        <p>
          Each skill runs independently and produces its own score. You can
          enable or disable skills in the Skills page.
        </p>
      </Prose>
      <div className="mt-4 space-y-3">
        {skills.map((s) => (
          <Card key={s.name}>
            <CardHeader className="pb-2">
              <div className="flex items-center gap-2">
                <CardTitle className="text-sm">{s.name}</CardTitle>
                <Badge variant="secondary">{s.engine}</Badge>
                <span className="text-xs text-muted-foreground ml-auto">
                  Cost: {s.cost}
                </span>
              </div>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">{s.desc}</p>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

function ScoreGuide() {
  return (
    <div>
      <SectionHeading>Score Guide</SectionHeading>
      <Prose>
        <p>
          Each skill produces an independent score from 0 to 100. The overall
          check score is calculated as the arithmetic average of all enabled
          skill scores.
        </p>
      </Prose>

      <SubHeading>Verdicts</SubHeading>
      <Prose>
        <p>
          Each score is mapped to a verdict based on configurable thresholds
          (default values shown):
        </p>
      </Prose>
      <ul className="mt-2 space-y-1.5 text-sm text-muted-foreground list-disc pl-5">
        <li>
          <strong>Pass</strong> (score &ge; 75): The article meets quality
          standards for this skill.
        </li>
        <li>
          <strong>Warn</strong> (score &ge; 50 and &lt; 75): The article has
          issues that should be reviewed but may not be blocking.
        </li>
        <li>
          <strong>Fail</strong> (score &lt; 50): Significant issues detected
          that likely need to be addressed before publishing.
        </li>
      </ul>

      <SubHeading>Custom thresholds</SubHeading>
      <Prose>
        <p>
          You can customize pass and warn thresholds per skill in the Settings
          page. For example, you might set a stricter threshold for plagiarism
          (pass: 90, warn: 70) while keeping a relaxed threshold for SEO (pass:
          60, warn: 40).
        </p>
      </Prose>
    </div>
  );
}

function ApiKeysSetup() {
  return (
    <div>
      <SectionHeading>API Keys Setup</SectionHeading>
      <Prose>
        <p>
          You can configure keys either through the Settings page or via
          environment variables. Environment variables take precedence over
          stored config.
        </p>
      </Prose>

      <SubHeading>Copyscape</SubHeading>
      <Prose>
        <p>Required for Plagiarism Check and AI Detection skills.</p>
      </Prose>
      <ol className="mt-1 space-y-1 text-sm text-muted-foreground list-decimal pl-5">
        <li>Sign up at copyscape.com/apiconfigure.php</li>
        <li>Note your username and API key</li>
        <li>Enter both in Settings &rarr; API Keys, or set COPYSCAPE_USER and COPYSCAPE_KEY environment variables</li>
      </ol>

      <SubHeading>Exa AI</SubHeading>
      <Prose>
        <p>Required for Fact Check skill (evidence search).</p>
      </Prose>
      <ol className="mt-1 space-y-1 text-sm text-muted-foreground list-decimal pl-5">
        <li>Sign up at dashboard.exa.ai</li>
        <li>Generate an API key</li>
        <li>Enter in Settings or set EXA_API_KEY</li>
      </ol>

      <SubHeading>MiniMax</SubHeading>
      <Prose>
        <p>
          Required for Fact Check, Tone of Voice, Legal Risk, and Content
          Summary.
        </p>
      </Prose>
      <ol className="mt-1 space-y-1 text-sm text-muted-foreground list-decimal pl-5">
        <li>Sign up at platform.minimaxi.com</li>
        <li>Generate an API key</li>
        <li>Enter in Settings or set MINIMAX_API_KEY</li>
      </ol>

      <SubHeading>Anthropic</SubHeading>
      <Prose>
        <p>Optional alternative LLM provider (select in Settings &rarr; LLM Provider).</p>
      </Prose>
      <ol className="mt-1 space-y-1 text-sm text-muted-foreground list-decimal pl-5">
        <li>Sign up at console.anthropic.com</li>
        <li>Generate an API key</li>
        <li>Enter in Settings or set ANTHROPIC_API_KEY</li>
      </ol>
    </div>
  );
}

function CliReference() {
  return (
    <div>
      <SectionHeading>CLI Reference</SectionHeading>

      <SubHeading>Basic usage</SubHeading>
      <CodeBlock>{`bun run article-checker <file>`}</CodeBlock>
      <Prose>
        <p>
          Run all enabled checks on a single article file (.md or .txt).
        </p>
      </Prose>

      <SubHeading>Batch mode</SubHeading>
      <CodeBlock>{`bun run article-checker --batch <directory>`}</CodeBlock>
      <Prose>
        <p>
          Check all article files in a directory. Results are saved per-file.
        </p>
      </Prose>

      <SubHeading>Custom output</SubHeading>
      <CodeBlock>{`bun run article-checker <file> --output report.md`}</CodeBlock>
      <Prose>
        <p>Write results to a JSON file instead of the default location.</p>
      </Prose>

      <SubHeading>View history</SubHeading>
      <CodeBlock>{`bun run article-checker --history`}</CodeBlock>
      <Prose>
        <p>List all previous check results stored locally.</p>
      </Prose>

      <SubHeading>Interactive setup</SubHeading>
      <CodeBlock>{`bun run article-checker --setup`}</CodeBlock>
      <Prose>
        <p>
          Launch the setup wizard to configure API keys and skill preferences
          interactively.
        </p>
      </Prose>

      <SubHeading>Launch dashboard</SubHeading>
      <CodeBlock>{`bun run article-checker --ui`}</CodeBlock>
      <Prose>
        <p>Start the web dashboard on localhost:3000.</p>
      </Prose>

      <SubHeading>CI mode</SubHeading>
      <CodeBlock>{`bun run article-checker --ci ./article.md`}</CodeBlock>
      <Prose>
        <p>
          Run checks and exit with code 1 if any skill returns a fail verdict.
          Designed for CI/CD pipelines and automated quality gates.
        </p>
      </Prose>

      <SubHeading>JSON output</SubHeading>
      <CodeBlock>{`bun run article-checker --json ./article.md`}</CodeBlock>
      <Prose>
        <p>
          Output structured JSON instead of the terminal UI. Useful for scripts,
          agents, and piping results to other tools.
        </p>
      </Prose>

      <SubHeading>MCP server</SubHeading>
      <CodeBlock>{`bun run article-checker --mcp`}</CodeBlock>
      <Prose>
        <p>
          Start the MCP server for AI agent integration with Claude Code, Cursor,
          or Windsurf. Exposes 7 tools: check_article, list_reports, get_report,
          upload_context, list_contexts, get_skills, toggle_skill.
        </p>
      </Prose>

      <SubHeading>Context management</SubHeading>
      <CodeBlock>{`# Upload a tone guide
bun run article-checker context add tone-guide ./brand-voice.md

# Upload a content brief
bun run article-checker context add brief ./campaign-brief.md

# List all contexts
bun run article-checker context list

# View a context
bun run article-checker context show tone-guide

# Remove a context
bun run article-checker context remove brief`}</CodeBlock>
      <Prose>
        <p>
          Manage context documents (tone guides, briefs, legal policies) that
          skills use during checks. Contexts can also be managed from the
          Contexts page in the dashboard.
        </p>
      </Prose>
    </div>
  );
}

function Faq() {
  const faqs = [
    {
      q: "Where is my data stored?",
      a: "All data is stored locally at ~/.article-checker/. This includes your config file (config.json), check history database (history.db), and any cached results. Nothing is stored on remote servers by Article Checker itself.",
    },
    {
      q: "What's the cost per check?",
      a: "With all skills enabled, a typical check costs approximately $0.22 USD. The SEO Analysis skill is free (runs offline). Copyscape skills cost ~$0.09 each, and MiniMax-based skills cost ~$0.01 each. Exa AI search for fact checking costs ~$0.02.",
    },
    {
      q: "Can I add custom skills?",
      a: "Yes. See docs/custom-skills.md in the repository for instructions on creating a custom skill module. Custom skills follow the same interface: receive article text, return a score (0-100), verdict, summary, and findings array.",
    },
    {
      q: "Is my article text sent to third parties?",
      a: "Yes, when using external skills. Copyscape receives the article text for plagiarism and AI detection. Exa AI receives extracted claims for evidence search. MiniMax receives the text for tone, legal, fact-check, and summary analysis. All communication is over HTTPS.",
    },
    {
      q: "Can I use it offline?",
      a: "Only the SEO Analysis skill works offline. All other skills require internet access and valid API keys for their respective services.",
    },
    {
      q: "How do I update Article Checker?",
      a: "Pull the latest version from the repository and run bun install. Your config and history data will be preserved across updates.",
    },
  ];

  return (
    <div>
      <SectionHeading>Frequently Asked Questions</SectionHeading>
      <div className="mt-4 space-y-4">
        {faqs.map((faq) => (
          <div key={faq.q}>
            <h3 className="text-sm font-semibold">{faq.q}</h3>
            <p className="mt-1 text-sm text-muted-foreground">{faq.a}</p>
          </div>
        ))}
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* Main page                                                           */
/* ------------------------------------------------------------------ */

export default function DocsPage() {
  return (
    <div className="flex flex-1 flex-col">
      <div className="flex-1 px-8 py-10">
        <h1 className="text-2xl font-semibold tracking-tight">
          Documentation
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Learn how to use Article Checker -- from first check to advanced
          configuration.
        </p>

        <div className="mt-6 max-w-3xl">
          <Tabs defaultValue={0}>
            <TabsList>
              <TabsTrigger value={0}>Getting Started</TabsTrigger>
              <TabsTrigger value={1}>Skills</TabsTrigger>
              <TabsTrigger value={2}>Scores</TabsTrigger>
              <TabsTrigger value={3}>API Keys</TabsTrigger>
              <TabsTrigger value={4}>CLI</TabsTrigger>
              <TabsTrigger value={5}>FAQ</TabsTrigger>
            </TabsList>

            <TabsContent value={0} className="mt-6">
              <GettingStarted />
            </TabsContent>
            <TabsContent value={1} className="mt-6">
              <SkillsReference />
            </TabsContent>
            <TabsContent value={2} className="mt-6">
              <ScoreGuide />
            </TabsContent>
            <TabsContent value={3} className="mt-6">
              <ApiKeysSetup />
            </TabsContent>
            <TabsContent value={4} className="mt-6">
              <CliReference />
            </TabsContent>
            <TabsContent value={5} className="mt-6">
              <Faq />
            </TabsContent>
          </Tabs>
        </div>
      </div>
      <FooterBar />
    </div>
  );
}
