import type { CheckRecord } from "./db.ts";
import type { SkillResult } from "./skills/types.ts";
import { generateReport } from "./report.ts";
import { writeFileSync } from "fs";

const VERDICT_ICON: Record<string, string> = { pass: "✅", warn: "⚠️", fail: "❌" };
const SEVERITY_ICON: Record<string, string> = { info: "ℹ️", warn: "⚠️", error: "❌" };

export function generateMarkdownReport(record: Omit<CheckRecord, "id" | "createdAt"> & { createdAt?: string }): string {
  const overallScore = record.results.length > 0
    ? Math.round(record.results.reduce((s, r) => s + r.score, 0) / record.results.length)
    : 0;
  const overallVerdict = record.results.some(r => r.verdict === "fail") ? "fail"
    : record.results.some(r => r.verdict === "warn") ? "warn" : "pass";
  const now = record.createdAt ?? new Date().toISOString().slice(0, 16);

  let md = `# Article Checker Report\n\n`;
  md += `**Source:** ${record.source}\n`;
  md += `**Words:** ${record.wordCount.toLocaleString()}\n`;
  md += `**Date:** ${now}\n`;
  md += `**API cost:** $${record.totalCostUsd.toFixed(3)}\n`;
  md += `**Overall:** ${overallScore}/100 ${VERDICT_ICON[overallVerdict] ?? ""} ${overallVerdict.toUpperCase()}\n\n`;
  md += `---\n\n`;

  for (const r of record.results) {
    md += `## ${VERDICT_ICON[r.verdict] ?? ""} ${r.name} — ${r.score}/100 ${r.verdict.toUpperCase()}\n\n`;
    md += `${r.summary}\n\n`;
    const visible = r.findings.filter(f => f.severity === "warn" || f.severity === "error");
    if (visible.length > 0) {
      for (const f of visible) {
        md += `- ${SEVERITY_ICON[f.severity] ?? ""} ${f.text}\n`;
        if (f.quote) md += `  > "${f.quote.slice(0, 140)}${f.quote.length > 140 ? "…" : ""}"\n`;
      }
      md += `\n`;
    }
  }

  md += `---\n\n`;
  md += `*Generated by [Article Checker](https://github.com/sharonds/article-checker) — MIT License*\n`;
  return md;
}

export function exportReport(
  record: Omit<CheckRecord, "id" | "createdAt"> & { createdAt?: string },
  outputPath: string
): void {
  if (outputPath.endsWith(".md")) {
    writeFileSync(outputPath, generateMarkdownReport(record));
  } else {
    // Default to HTML
    writeFileSync(outputPath, generateReport(record));
  }
}
